environment: usdfdev
fqdn: usdf-rsp-dev.slac.stanford.edu
vaultPathPrefix: secret/rubin/usdf-rsp-dev
# butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-repos.yaml"
repoURL: https://github.com/lsst-sqre/phalanx.git

argo-workflows:
  enabled: false
vault-secrets-operator:
  enabled: true
